webjars:
  bootstrap: "4.5.0"
  jquery: "3.5.1"
spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/test?serverTimezone=JST"
    username: "InputUsername"
    password: "InputPassword"
    driver-class-name: "com.mysql.jdbc.Driver"
